### ISSUE TITLE
qrPrint Black string as argument

### ISSUE THREAD

**Issue by juancarlospaco** [ThomasTJdev/nim_qr#2]
I want to pass the Black string as argument instead of hardcoded `"##"`,
maybe have `"##"` as default argument, so I can pass `"⬛⬛"` or others.

```nim
qrPrint("hello", black = "⬛⬛")
```

**Comment by ThomasTJdev** [comment]
Fine by me, it's only my old XFCE which does not support those fancy things. 

PR ? :)

**Comment by juancarlospaco** [comment]
https://github.com/ThomasTJdev/nim_qr/pull/3
